# Generated by Django 4.1.3 on 2022-11-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PARKID', models.CharField(max_length=100)),
                ('PARKSEAT', models.CharField(max_length=100)),
                ('CARNUM', models.CharField(max_length=100)),
                ('DATE', models.CharField(default='YYYY-MM-DD', max_length=10)),
            ],
        ),
    ]
