apiVersion: v1
kind: ConfigMap
metadata:
  namespace: logging
  name: elasticsearch-config
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |-
    cluster.name: ${CLUSTER_NAME}
    network.host: 0.0.0.0

